source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'rails-api'

gem 'pg'
gem 'dotenv-rails'
gem 'responders'
gem 'passenger'
gem 'active_model_serializers'

gem 'carrierwave', '0.10.0'
gem 'carrierwave-base64'
gem 'mini_magick'
gem 'fog'

gem 'devise'

group :development do
  gem 'spring'
end

group :production do
  gem 'rails_12factor'
end